<?php
require_once '../models/Student.php';
require_once '../models/StudentHistory.php';
require_once '../models/Class.php';

class ReportController {
    private $db;
    private $student;
    private $history;
    private $class;

    public function __construct($db) {
        $this->db = $db;
        $this->student = new Student($db);
        $this->history = new StudentHistory($db);
        $this->class = new ClassModel($db);
    }

    public function index() {
        $page_title = "Reports | Student Management System";
        $active_page = "reports";
        $classes = $this->class->readAll();
        $class_stats = $this->history->getClassStatistics();
        
        // Get gender statistics
        $male_count = $this->getGenderCount('Male');
        $female_count = $this->getGenderCount('Female');
        
        require_once '../views/layouts/header.php';
        require_once '../views/layouts/sidebar.php';
        require_once '../views/reports/index.php';
        require_once '../views/layouts/footer.php';
    }
    
    public function export() {
        $format = $_GET['format'] ?? 'excel';
        $class_id = $_GET['class_id'] ?? null;
        
        $students = $this->student->readAll(10000, 0, '', $class_id);
        
        if($format == 'excel') {
            $this->exportToExcel($students);
        } else {
            $this->exportToPDF($students);
        }
    }
    
    private function getGenderCount($gender) {
        $query = "SELECT COUNT(*) as count FROM students WHERE gender = :gender AND is_deleted = 0";
        $stmt = $this->db->prepare($query);
        $stmt->bindParam(':gender', $gender);
        $stmt->execute();
        $result = $stmt->fetch(PDO::FETCH_ASSOC);
        return $result['count'];
    }
    
    private function exportToExcel($students) {
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment; filename="students_report_' . date('Y-m-d') . '.xls"');
        
        echo "Registration Number\tFirst Name\tLast Name\tGender\tDate of Birth\tParent Name\tParent Phone\tCurrent Class\tAdmission Date\n";
        
        while($student = $students->fetch(PDO::FETCH_ASSOC)) {
            echo $student['registration_number'] . "\t";
            echo $student['first_name'] . "\t";
            echo $student['last_name'] . "\t";
            echo $student['gender'] . "\t";
            echo $student['date_of_birth'] . "\t";
            echo $student['parent_name'] . "\t";
            echo $student['parent_phone'] . "\t";
            echo ($student['class_name'] ?? 'Not Assigned') . "\t";
            echo $student['admission_date'] . "\n";
        }
        exit();
    }
    
    private function exportToPDF($students) {
        header('Content-Type: text/html');
        header('Content-Disposition: attachment; filename="students_report_' . date('Y-m-d') . '.html"');
        
        echo "<html><head>";
        echo "<title>Students Report</title>";
        echo "<style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #667eea; text-align: center; }
            table { border-collapse: collapse; width: 100%; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #667eea; color: white; }
            tr:nth-child(even) { background-color: #f2f2f2; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
        </style>";
        echo "</head><body>";
        echo "<h1>Student Management System</h1>";
        echo "<h3>Students Report - " . date('F d, Y') . "</h3>";
        echo "<table>";
        echo "<thead><tr>";
        echo "<th>Reg Number</th><th>First Name</th><th>Last Name</th><th>Gender</th>";
        echo "<th>Date of Birth</th><th>Parent Name</th><th>Parent Phone</th><th>Current Class</th><th>Admission Date</th>";
        echo "</tr></thead><tbody>";
        
        while($student = $students->fetch(PDO::FETCH_ASSOC)) {
            echo "<tr>";
            echo "<td>{$student['registration_number']}</td>";
            echo "<td>{$student['first_name']}</td>";
            echo "<td>{$student['last_name']}</td>";
            echo "<td>{$student['gender']}</td>";
            echo "<td>{$student['date_of_birth']}</td>";
            echo "<td>{$student['parent_name']}</td>";
            echo "<td>{$student['parent_phone']}</td>";
            echo "<td>{$student['class_name'] ?? 'Not Assigned'}</td>";
            echo "<td>{$student['admission_date']}</td>";
            echo "</tr>";
        }
        
        echo "</tbody></table>";
        echo "<div class='footer'>Generated by Student Management System on " . date('Y-m-d H:i:s') . "</div>";
        echo "</body></html>";
        exit();
    }
}
?>